namespace: monitoring

replicaCount: 1

image:
  repository: docker.io/bitnami/prometheus
  tag: 3.4.1-debian-12-r2
  pullPolicy: IfNotPresent

serviceAccount:
  create: true
  name: prometheus-server

service:
  type: NodePort
  port: 80
  targetPort: 9090
  nodePort: 30001  # set nodePort number or leave null for auto

resources:
  limits:
    memory: 400Mi
  requests:
    memory: 200Mi

nodeSelector:
  kubernetes.io/hostname: k8s-master

tolerations:
  - key: node-role.kubernetes.io/control-plane
    operator: Exists
    effect: NoSchedule

securityContext:
  fsGroup: 1001

config:
  retentionTime: 10d
