apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-server
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/component: server
data:
  prometheus.yaml: |-
    global:
      external_labels:
        monitor: prometheus
    alerting:
      alertmanagers:
        - static_configs:
            - targets: ['alertmanager.monitoring.svc.cluster.local:9093']
    rule_files:
      - /etc/prometheus/rules.yaml
    scrape_configs:
      - job_name: prometheus
        kubernetes_sd_configs:
          - role: endpoints
            namespaces:
              names:
                - {{ .Values.namespace }}
        metrics_path: /metrics
        relabel_configs:
          - source_labels: [job]
            target_label: __tmp_prometheus_job_name
          - action: keep
            source_labels:
              - __meta_kubernetes_service_label_app_kubernetes_io_component
              - __meta_kubernetes_service_labelpresent_app_kubernetes_io_component
            regex: (server);true
          - action: keep
            source_labels:
              - __meta_kubernetes_service_label_app_kubernetes_io_instance
              - __meta_kubernetes_service_labelpresent_app_kubernetes_io_instance
            regex: (prometheus);true
          - action: keep
            source_labels:
              - __meta_kubernetes_service_label_app_kubernetes_io_name
              - __meta_kubernetes_service_labelpresent_app_kubernetes_io_name
            regex: (prometheus);true
          - action: keep
            source_labels:
              - __meta_kubernetes_endpoint_port_name
            regex: http
          - source_labels:
              - __meta_kubernetes_endpoint_address_target_kind
              - __meta_kubernetes_endpoint_address_target_name
            separator: ;
            regex: Node;(.*)
            replacement: ${1}
            target_label: node
          - source_labels:
              - __meta_kubernetes_endpoint_address_target_kind
              - __meta_kubernetes_endpoint_address_target_name
            separator: ;
            regex: Pod;(.*)
            replacement: ${1}
            target_label: pod
          - source_labels:
              - __meta_kubernetes_namespace
            target_label: namespace
          - source_labels:
              - __meta_kubernetes_service_name
            target_label: service
          - source_labels:
              - __meta_kubernetes_pod_name
            target_label: pod
          - source_labels:
              - __meta_kubernetes_pod_container_name
            target_label: container
          - action: drop
            source_labels:
              - __meta_kubernetes_pod_phase
            regex: (Failed|Succeeded)
          - source_labels:
              - __meta_kubernetes_service_name
            target_label: job
            replacement: ${1}
          - target_label: endpoint
            replacement: http
          - source_labels:
              - __address__
            target_label: __tmp_hash
            modulus: 1
            action: hashmod
      - job_name: 'node-exporter'
        kubernetes_sd_configs:
          - role: endpoints
        relabel_configs:
          - source_labels: [__meta_kubernetes_service_label_app_kubernetes_io_name]
            regex: prometheus-node-exporter
            action: keep
          - source_labels: [__meta_kubernetes_namespace]
            target_label: namespace
          - source_labels: [__meta_kubernetes_service_name]
            target_label: service
          - source_labels: [__meta_kubernetes_pod_name]
            target_label: pod
          - source_labels: [__address__]
            target_label: instance
      - job_name: 'kube-state-metrics'
        kubernetes_sd_configs:
          - role: endpoints
        relabel_configs:
          - source_labels: [__meta_kubernetes_service_label_app_kubernetes_io_name]
            regex: kube-state-metrics
            action: keep
          - source_labels: [__meta_kubernetes_namespace]
            target_label: namespace
          - source_labels: [__meta_kubernetes_service_name]
            target_label: service
          - source_labels: [__meta_kubernetes_pod_name]
            target_label: pod
          - source_labels: [__address__]
            target_label: instance
  rules.yaml: |-
    groups:
      - name: Always-Firing-Alert
        rules:
          - alert: AlwaysFiring
            expr: vector(1)
            for: 10s
            labels:
              severity: test
            annotations:
              summary: "This is a test alert that always fires"
              description: "This alert is firing just to test the end-to-end setup"

